/**
 * Per-face ice power assets — isolated from the 3×2 sheet so neighboring
 * cubes/drips never bleed into another die's overlay.
 *
 * Regenerated by: node scripts/split-ice-power-faces.mjs
 * Pad fraction must match ice_power_face_meta.json (pad / outSize).
 */

/** Pad on each side as a fraction of the square face canvas (from split meta). */
export const ICE_FACE_PAD_FRAC = 0.179487;

/** Source sheet (3×2) — kept for lab reference / regen. */
export const ICE_POWER_FROZEN_SHEET_URL = "/assets/ice_power_frozen.png";
export const ICE_POWER_OUTLINE_SHEET_URL = "/assets/ice_power_frozen_outline.png";
export const ICE_POWER_OUTLINE_DRIPS_SHEET_URL = "/assets/ice_power_frozen_outline_drips.png";

function clampFace(value) {
  const n = Math.round(Number(value));
  if (!Number.isFinite(n)) return 1;
  return Math.min(6, Math.max(1, n));
}

export function icePowerFrozenFaceUrl(faceValue) {
  return `/assets/ice_power_frozen_face_${clampFace(faceValue)}.png`;
}

export function icePowerOutlineFaceUrl(faceValue) {
  return `/assets/ice_power_frozen_outline_face_${clampFace(faceValue)}.png`;
}

export function icePowerOutlineDripsFaceUrl(faceValue) {
  return `/assets/ice_power_frozen_outline_drips_face_${clampFace(faceValue)}.png`;
}
