require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

# Xcode 26+ may select the Metal toolchain, which has no Swift stdlib folder.
SWIFT_LIBRARY_SEARCH_PATHS = [
  '$(inherited)',
  '$(SDKROOT)/usr/lib/swift',
].freeze

DEFAULT_XCODE_TOOLCHAIN = '$(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain'

def fix_swift_library_search_paths!(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['LIBRARY_SEARCH_PATHS'] = SWIFT_LIBRARY_SEARCH_PATHS
      config.build_settings['TOOLCHAIN_DIR'] = DEFAULT_XCODE_TOOLCHAIN
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each do |config_name, xcconfig|
      xcconfig.attributes['LIBRARY_SEARCH_PATHS'] = SWIFT_LIBRARY_SEARCH_PATHS.join(' ')
      path = aggregate_target.xcconfig_path(config_name)
      xcconfig.save_as(path)
    end
  end

  Dir.glob(File.join(__dir__, 'Pods', 'Target Support Files', '**', '*.xcconfig')).each do |path|
    contents = File.read(path)
    next unless contents.include?('LIBRARY_SEARCH_PATHS')

    updated = contents.gsub(
      /^LIBRARY_SEARCH_PATHS = .*\n/,
      "LIBRARY_SEARCH_PATHS = $(inherited) $(SDKROOT)/usr/lib/swift\n"
    )
    File.write(path, updated) if updated != contents
  end

  frameworks_sh = File.join(__dir__, 'Pods', 'Target Support Files', 'Pods-App', 'Pods-App-frameworks.sh')
  if File.exist?(frameworks_sh)
    contents = File.read(frameworks_sh)
    updated = contents.gsub(
      'SWIFT_STDLIB_PATH="${TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}"',
      'SWIFT_STDLIB_PATH="${SDKROOT}/usr/lib/swift"'
    )
    File.write(frameworks_sh, updated) if updated != contents
  end
end

# Xcode 26 enables explicit Swift modules by default; CocoaPods + Capacitor need this off.
def disable_explicit_swift_modules!(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      end
    end
    aggregate_target.user_project.build_configurations.each do |config|
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end
    aggregate_target.user_project.save
  end
end

post_install do |installer|
  assertDeploymentTarget(installer)
  fix_swift_library_search_paths!(installer)
  disable_explicit_swift_modules!(installer)
end
